---

- name: Deploy project stack into swarm cluster
  become_user: "dockeradmin"
  docker_stack:
    state: present
    name: "{{ project_name }}"
    compose:
      - "{{ dockeradmin_home }}/{{ project_name }}/docker-compose.yml"
